name: Deploy AWS CDK

on:
  push:
  
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credential@v1
    #   with:
    #   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   aws-region: eu-west-2

    - name: Install npm Back End
      run: 'npm install'
      working-directory: back-end

    - name: Run Server
      run: 'node local.js'
      working-directory: back-end

    - name: Install npm Front End
      run: 'npm install'
      working-directory: front-end

    - name: Run npm Build
      run: 'npm run build'
      working-directory: front-end

    - name: Install npm Infrastructure
      run: npm install
      working-directory: infrastructure

    - name: AWS Login
      run: 'awz-azure-login --profile aal-profile --mode=gui'
      working-directory: infrastructure

    - name: CDK Deploy
      run: 'cdk --profile aal-profile deploy'
      working-directory: infrastructure

        
