name: Docker React CI Back End

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      working-directory: back-end

    - name: Build the Docker image
      run: docker build -t khaashifriaz/api2:v1 .
      working-directory: back-end

    - name: Push the docker image
      run: docker push khaashifriaz/api2:v1
      working-directory: back-end