name: test app

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install front
      run: npm install
      working-directory: front-end

    - name: lint front
      run: 'npm run lint'
      working-directory: front-end

    - name: test front
      run: npm test
      working-directory: front-end

    - name: npm install back
      run: npm install
      working-directory: back-end

    - name: lint back
      run: 'npm run lint'
      working-directory: back-end

    - name: test back
      run: npm test
      working-directory: back-end

    - name: run front end
      run: 'npm run build'
      working-directory: front-end
